data <- c(10,5,6,20,7,30,9,4)
print("Dataset: ")
print(data)
mean_value <- mean(data)
print(paste("Mean =",mean_value))
median_value <- median(data)
print(paste("Median =", median_value))
mode_function <- function(x){
	uniq_values <-unique(x)
	uniq_values[which.max(tabulate(match(x,uniq_values)))]
}
mode_value <- mode_function(data)
print(paste("Mode =",mode_value))
max_value <- max(data)
print(paste("Maximum =",max_value))
min_value <- min(data)
print(paste("Minimum =",min_value))
var_value <- var(data)
print(paste("Varience =",var_value))
sd_value <- sd(data)
print(paste("Standard Deviation =",sd_value))
visual <- barplot(data)
print(paste("Bar Plot",visual))
b<- summary(data)
print(paste("Summary",b))
pie_chart <- pie(data)
print(paste("Pie Chart",pie_chart))
